version: '3.8'

services:
db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopware
      MYSQL_USER: $SERVICE_USER_DB
      MYSQL_PASSWORD: $SERVICE_PASSWORD_DB
    volumes:
      - shopware-db:/var/lib/mysql

  php:
    build:
      context: ./phase2
      dockerfile: php.Dockerfile
    restart: unless-stopped
    volumes:
      - shopware-data:/var/www/html
    environment:
      APP_ENV: prod
      APP_URL: ${SERVICE_FQDN_NGINX:-https://shopware1.myhobby-ki.de}
      PHP_MEMORY_LIMIT: 512M
    depends_on:
      - db

  nginx:
    build:
      context: ./phase2
      dockerfile: nginx.Dockerfile
    restart: unless-stopped
    volumes:
      - shopware-data:/var/www/html
    depends_on:
      - php
    environment:
      APP_URL: ${SERVICE_FQDN_NGINX:-https://shopware1.myhobby-ki.de}

volumes:
  shopware-db:
  shopware-data: